Refine script.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -109,3 +109,9 @@ jobs:
                 registry.cn-hangzhou.aliyuncs.com/ossrs/web:$SRS_MAJOR
             END
             bash /root/restart_docs-statics.sh
+            #
+            # Cleanup old docker images.
+            for image in $(docker images |grep '<none>' |awk '{print $3}'); do
+              docker rmi -f $image
+              echo "Remove image $image, r0=$?"
+            done
